name: Generate Snake

on:
  workflow_dispatch:  # Ermöglicht die manuelle Ausführung

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Generate the snake animation
      - name: Generate Snake Animation
        uses: Platane/snk@v1
        with:
          github_user_name: Marc-Braun-72
