name: Generate Snake

on:
  schedule:
    - cron: "0 5 * * *"  
  workflow_dispatch:  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3 

      # Generate the snake animation
      - name: Generate Snake Animation
        uses: Platane/snk@v2
        with:
          github_user_name: Marc-Braun-72  

      # Push the snake animation to the output branch
      - name: Push Snake Animation to Output Branch
        uses: ad-m/github-push-action@master
        with:
          branch: output
          force: true
          directory: .
